//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_CAT_L4
    {
        public string COMPCODE { get; set; }
        public string CAT_L1 { get; set; }
        public string CAT_L2 { get; set; }
        public string CAT_L3 { get; set; }
        public string CAT_L4 { get; set; }
        public string CAT_DESC { get; set; }
        public string USERCODE { get; set; }
        public int REMOVE { get; set; }
        public int CHANGED { get; set; }
        public System.DateTime CHANGED_DATE { get; set; }
        public string CHANGED_USERCODE { get; set; }
    }
}
