//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_MAST
    {
        public string COMPCODE { get; set; }
        public string CAT_CODE { get; set; }
        public string CAT_DESC { get; set; }
        public string USERCODE { get; set; }
        public string GLCODE { get; set; }
        public string PURCH_GLCODE { get; set; }
        public int REMOVE { get; set; }
        public int CHANGED { get; set; }
        public System.DateTime CHANGEDDATE { get; set; }
    }
}
