//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_MAST
    {
        public string COMPCODE { get; set; }
        public string CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_ADDRESS1 { get; set; }
        public string CUST_ADDRESS2 { get; set; }
        public string CUST_PHONE { get; set; }
        public string CUST_EMAIL { get; set; }
        public string CUST_VATNO { get; set; }
        public string USERCODE { get; set; }
        public float CREDIT_PERIOD { get; set; }
        public float CREDIT_LIMIT { get; set; }
        public string GLCODE { get; set; }
        public Nullable<float> AR_OPBAL { get; set; }
        public Nullable<float> AR_OPBAL_BALANCE { get; set; }
        public string CUST_ADDRESS3 { get; set; }
        public string CUST_CONTACT_PERSON { get; set; }
        public string CUST_FAX { get; set; }
        public Nullable<int> ISVATEXCEMPTED { get; set; }
        public string OLD_GLCODE { get; set; }
        public string CUST_SVATNO { get; set; }
        public string REFNO { get; set; }
        public string AUDIT_MEMO { get; set; }
        public Nullable<System.DateTime> AUDIT_DATE { get; set; }
        public Nullable<int> IS_AUDITED { get; set; }
        public string CUST_TYPE { get; set; }
        public Nullable<double> CREDIT_BALANCE { get; set; }
    }
}
