//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_LEDGER
    {
        public string COMPCODE { get; set; }
        public string CUST_CODE { get; set; }
        public string TXN_TYPE { get; set; }
        public string DOC_NO { get; set; }
        public string CSH_CRD { get; set; }
        public string LOCA { get; set; }
        public System.DateTime TXN_DATE { get; set; }
        public decimal SEQ_NO { get; set; }
        public string REFNO { get; set; }
        public decimal TXN_TOTAL { get; set; }
        public decimal VAT_AMT { get; set; }
        public decimal NBT_AMT { get; set; }
        public decimal COST_AMT { get; set; }
        public decimal PAYABLE_AMT { get; set; }
        public decimal PAYABLE_BALANCE { get; set; }
        public string SETTLED_RECEIPT_NO { get; set; }
        public Nullable<System.DateTime> SETTLED_DATE { get; set; }
        public string SETTLED_USER { get; set; }
    }
}
