//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL
    {
        public string COMPCODE { get; set; }
        public string CAT_L1 { get; set; }
        public string CAT_L2 { get; set; }
        public string CAT_L3 { get; set; }
        public string CAT_L4 { get; set; }
        public string CAT_L5 { get; set; }
        public string GLCODE { get; set; }
        public string GLDESC { get; set; }
        public Nullable<int> IS_CONTROL_ACC { get; set; }
        public Nullable<int> IS_CASHBOOK { get; set; }
        public Nullable<int> IS_BANK { get; set; }
        public string TYPE_DR_CR { get; set; }
        public string BANK_ABR { get; set; }
        public decimal OPBAL { get; set; }
        public decimal BS_OPBAL { get; set; }
        public decimal BUDGET_AMT { get; set; }
        public Nullable<int> IS_PROTECTED { get; set; }
        public Nullable<System.DateTime> REC_UPTO_DATE { get; set; }
        public string USERCODE { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
        public string CHANGED_USERCODE { get; set; }
    }
}
