//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MAST
    {
        public string COMPCODE { get; set; }
        public string LOCA { get; set; }
        public string CSH_CRD { get; set; }
        public string INV_NO { get; set; }
        public string INV_TYPE { get; set; }
        public string CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public Nullable<System.DateTime> TXN_DATE { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public string TXN_TIME { get; set; }
        public string REF { get; set; }
        public string DN_NO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> IS_DISCOUNT_PER { get; set; }
        public Nullable<decimal> TOTAL_AFTER_DISCOUNT { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public Nullable<decimal> NBT_AMOUNT { get; set; }
        public Nullable<decimal> COST_AMOUNT { get; set; }
        public Nullable<decimal> DEDUCTIONS { get; set; }
        public Nullable<decimal> PAYABLE_AMOUNT { get; set; }
        public Nullable<decimal> PAY_BALANCE { get; set; }
        public Nullable<decimal> PAY_STATUS { get; set; }
        public Nullable<decimal> PAY_IN_PROGRESS { get; set; }
        public string VAT_CODE1 { get; set; }
        public string VAT_CODE2 { get; set; }
        public string BRANCH_CODE { get; set; }
        public string TERMINAL_ID { get; set; }
        public string INVOICE_E { get; set; }
        public string AMOUNT_IN_WORD { get; set; }
        public string USERCODE { get; set; }
        public Nullable<int> CANCELLED { get; set; }
        public string CANCEL_USERCODE { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_TIME { get; set; }
        public Nullable<decimal> PRINTED { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> DISCOUNT_AMT { get; set; }
    }
}
