//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_SUPP
    {
        public string COMPCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string LOCA_CODE { get; set; }
        public string SUPP_CODE { get; set; }
        public float P_PRICE { get; set; }
        public System.DateTime Last_Change_Date { get; set; }
    }
}
