//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MAST_004
    {
        public string ITEM { get; set; }
        public string DESC1 { get; set; }
        public string DESC2 { get; set; }
        public decimal PACK { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> ROL { get; set; }
        public Nullable<decimal> ROQ { get; set; }
        public Nullable<decimal> MAX_S { get; set; }
        public Nullable<decimal> MIN_S { get; set; }
        public Nullable<decimal> QIH { get; set; }
        public Nullable<decimal> BF_BAL { get; set; }
        public Nullable<decimal> CF_BAL { get; set; }
        public Nullable<decimal> COST_PRICE { get; set; }
        public Nullable<bool> IS_ROUND { get; set; }
        public Nullable<bool> IS_CUTTED { get; set; }
        public Nullable<int> CUT_STAT { get; set; }
        public decimal LENGTH { get; set; }
        public decimal WIDTH { get; set; }
        public string ITEM_UNIT1 { get; set; }
        public string ITEM_UNIT2 { get; set; }
        public Nullable<int> ACTUAL_COST { get; set; }
        public Nullable<int> IS_SERVICE_ITEM { get; set; }
        public Nullable<System.DateTime> LAST_CHANGE_DATE { get; set; }
        public decimal UNIT_1_QTY { get; set; }
        public decimal UNIT_2_QTY { get; set; }
        public Nullable<decimal> BACK_UNIT_1_QTY { get; set; }
        public Nullable<decimal> BACK_UNIT_2_QTY { get; set; }
        public Nullable<int> ACTIVE_STAT { get; set; }
        public Nullable<int> CHANGED { get; set; }
        public Nullable<decimal> UNIT_1_RESERVED_QTY { get; set; }
        public Nullable<decimal> UNIT_2_RESERVED_QTY { get; set; }
        public string COMPCODE { get; set; }
        public string LOCA_CODE { get; set; }
        public string CATCODE { get; set; }
        public string CATCODE_L2 { get; set; }
        public string CATCODE_L3 { get; set; }
        public string ITEM_UNIT0 { get; set; }
        public int Is_stocks_in_second__unit { get; set; }
        public string CATCODE_L4 { get; set; }
        public Nullable<decimal> SALES_PRICE_BULK { get; set; }
        public Nullable<decimal> SALES_PRICE_LOOSE { get; set; }
        public Nullable<decimal> COST_PRICE_BULK { get; set; }
        public Nullable<decimal> COST_PRICE_LOOSE { get; set; }
    }
}
