//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_CUTLIST
    {
        public string COMPCODE { get; set; }
        public string LOCA_CODE { get; set; }
        public string ITEM { get; set; }
        public string CUT_ITEM { get; set; }
    }
}
