//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCA_MAST
    {
        public string COMPCODE { get; set; }
        public string LOCA_CODE { get; set; }
        public string LOCA_DESCRIPT { get; set; }
        public string LOCA_LABEL { get; set; }
        public string PHY_NO { get; set; }
        public string INV_NO { get; set; }
        public string CASH_INV_NO { get; set; }
        public string CREDIT_INV_NO { get; set; }
        public string GRN_NO { get; set; }
        public string CUTNO { get; set; }
        public string TRANSNO { get; set; }
        public string ADJ_NO { get; set; }
        public string REC_NO { get; set; }
    }
}
