//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVIGATION
    {
        public string PARENT { get; set; }
        public string CHILD { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string PATH { get; set; }
        public int Unik { get; set; }
    }
}
