//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETWORK
    {
        public string CompName { get; set; }
        public Nullable<byte> IsBranch { get; set; }
        public string BranchCode { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string VatNo { get; set; }
        public string COMPCODE { get; set; }
        public Nullable<System.DateTime> SystemDate { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
    }
}
