//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHY_MAST
    {
        public string COMPCODE { get; set; }
        public string PHY_NO { get; set; }
        public string LOCA { get; set; }
        public string ITEM { get; set; }
        public System.DateTime PHY_DATE { get; set; }
        public string PHY_TIME { get; set; }
        public string USERCODE { get; set; }
        public decimal BULK_QTY { get; set; }
        public decimal LOOSE_QTY { get; set; }
    }
}
