//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_TYPES
    {
        public string COMPCODE { get; set; }
        public string TXN_TYPE { get; set; }
        public string PRICE_CODE { get; set; }
        public string PRICE_NAME { get; set; }
    }
}
