//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_MAST
    {
        public string COMPCODE { get; set; }
        public string REC_NO { get; set; }
        public System.DateTime REC_DATE { get; set; }
        public string REC_TIME { get; set; }
        public string CUST { get; set; }
        public string CUST_NAME { get; set; }
        public string REFNO { get; set; }
        public string REFSYS { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal TOTCHQS { get; set; }
        public decimal TOTCASH { get; set; }
        public string REC_MEMO { get; set; }
        public string DEPBANK { get; set; }
        public string GLCSHDB { get; set; }
        public string GLCHQDB { get; set; }
        public string USERCODE { get; set; }
        public int CANCEL { get; set; }
        public string CUSER { get; set; }
        public int PRINTED { get; set; }
        public int POSTED { get; set; }
        public int CANPOSTED { get; set; }
        public int ISREBANK { get; set; }
        public decimal OVERPAYMENT { get; set; }
        public string PAY_TYPE { get; set; }
        public string REC_TYPE { get; set; }
        public Nullable<int> ISADVANCE { get; set; }
        public Nullable<decimal> BALANCE_AMT { get; set; }
        public string AMOUNT_IN_WORDS { get; set; }
        public string REFERENCE_DETAILS { get; set; }
        public Nullable<int> IS_ALL_CASH { get; set; }
        public Nullable<int> IS_ALL_BANK { get; set; }
        public string DIRECT_SETTLE_USER { get; set; }
        public Nullable<System.DateTime> DIRECT_SETTLE_DATE { get; set; }
        public string DIRECT_SETTLE_TIME { get; set; }
    }
}
