//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_INV
    {
        public string COMPCODE { get; set; }
        public string REC_NO { get; set; }
        public string REC_TYPE { get; set; }
        public string INV_NO { get; set; }
        public string CSH_CRD { get; set; }
        public string LOCA { get; set; }
        public System.DateTime TXN_DATE { get; set; }
        public decimal SETTLED_AMT { get; set; }
        public decimal BAL_AMT { get; set; }
        public int SEQ_NO { get; set; }
    }
}
