//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        public string COMPCODE { get; set; }
        public string LOCA { get; set; }
        public string ITEM { get; set; }
        public string TXN_TYPE { get; set; }
        public string DOC_NO { get; set; }
        public string CSH_CRD { get; set; }
        public string LOCA_TO { get; set; }
        public string UNIT { get; set; }
        public string LOCA_TO_DESC { get; set; }
        public System.DateTime TXN_DATE { get; set; }
        public decimal SEQ_NO { get; set; }
        public string REFNO { get; set; }
        public decimal PURCHASE_PRICE { get; set; }
        public decimal COST_PRICE { get; set; }
        public string BULK_UNIT { get; set; }
        public string LOOSE_UNIT { get; set; }
        public decimal BULK_QTY { get; set; }
        public decimal LOOSE_QTY { get; set; }
        public decimal DOC_BAL_BULK_QTY { get; set; }
        public decimal DOC_BAL_LOOSE_QTY { get; set; }
        public string STOCK_TYPE { get; set; }
        public int IS_MONTH_END { get; set; }
        public decimal SEQ_NO_FULL { get; set; }
    }
}
