//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPP_MAST
    {
        public string COMCODE { get; set; }
        public string SUPP_CODE { get; set; }
        public string SUPP_NAME { get; set; }
        public string SUPP_ADDRESS1 { get; set; }
        public string SUPP_ADDRESS2 { get; set; }
        public string SUPP_PHONE { get; set; }
        public string SUPP_EMAIL { get; set; }
        public string USERCODE { get; set; }
        public float CREDIT_LIMIT { get; set; }
        public float CREDIT_PERIOD { get; set; }
        public string GLCODE { get; set; }
        public float AP_OPBAL { get; set; }
        public float AP_OPBAL_BALANCE { get; set; }
        public string SUPP_FAX { get; set; }
        public string SUPP_ADDRESS3 { get; set; }
        public string SUPP_CONTACT_PERSON { get; set; }
        public string SUPP_VATNO { get; set; }
        public string OLD_GLCODE { get; set; }
    }
}
