//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_DETAIL
    {
        public string COMPCODE { get; set; }
        public string LOCA_FROM { get; set; }
        public string TRANS_NO { get; set; }
        public string ITEM_LOCA { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public string ITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string BULK_UNIT { get; set; }
        public string LOOSE_UNIT { get; set; }
        public Nullable<decimal> BULK_SALES_PRICE { get; set; }
        public Nullable<decimal> LOOSE_SALES_PRICE { get; set; }
        public Nullable<decimal> BULK_QTY { get; set; }
        public Nullable<decimal> LOOSE_QTY { get; set; }
        public decimal IS_DISCOUNT_PER { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> DISCOUNT_AMT { get; set; }
    }
}
