//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_MAST
    {
        public string COMPCODE { get; set; }
        public string LOCA_FROM { get; set; }
        public string LOCA_TO { get; set; }
        public string TRANS_NO { get; set; }
        public string NOTE01 { get; set; }
        public string NOTE02 { get; set; }
        public Nullable<decimal> SEQNO_01 { get; set; }
        public Nullable<decimal> SEQNO_02 { get; set; }
        public Nullable<decimal> SEQNO_03 { get; set; }
        public string SEQREF_01 { get; set; }
        public string SEQREF_02 { get; set; }
        public string SEQREF_03 { get; set; }
        public Nullable<System.DateTime> TXN_DATE { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public string TXN_TIME { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> IS_DISCOUNT_PER { get; set; }
        public Nullable<decimal> TOTAL_AFTER_DISCOUNT { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public Nullable<decimal> NBT_AMOUNT { get; set; }
        public Nullable<decimal> COST_AMOUNT { get; set; }
        public Nullable<decimal> PAYABLE_AMOUNT { get; set; }
        public Nullable<decimal> PAY_BALANCE { get; set; }
        public Nullable<decimal> PAY_STATUS { get; set; }
        public Nullable<decimal> PAY_IN_PROGRESS { get; set; }
        public string VAT_CODE1 { get; set; }
        public string VAT_CODE2 { get; set; }
        public string BRANCH_CODE { get; set; }
        public string TERMINAL_ID { get; set; }
        public string USERCODE { get; set; }
        public Nullable<int> CANCELLED { get; set; }
        public string CANCEL_USERCODE { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_TIME { get; set; }
        public Nullable<decimal> PRINTED { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> DISCOUNT_AMT { get; set; }
        public Nullable<int> ACCEPTED { get; set; }
        public string ACCEPT_USERCODE { get; set; }
        public Nullable<System.DateTime> ACCEPT_DATE { get; set; }
        public string ACCEPT_TIME { get; set; }
        public string ACCEPT_BRANCH_CODE { get; set; }
        public string ACCEPT_TERMINAL_ID { get; set; }
    }
}
