//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT_MAST
    {
        public string COMPCODE { get; set; }
        public string UNIT_CODE { get; set; }
        public string UNIT_DESC { get; set; }
    }
}
