//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuLinERP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        public string FullName { get; set; }
        public string Address { get; set; }
        public string NIC { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Password { get; set; }
        public string USERCODE { get; set; }
        public string UserLevel { get; set; }
        public string RightCodes { get; set; }
        public string DepartmentCode { get; set; }
        public string DesignationCode { get; set; }
        public string COMPCODE { get; set; }
        public string AllowedLocations { get; set; }
    }
}
